export const CHANGE_INPUT_VALUE = 'CAHNGE_INPUT_VALUE'
export const ADD_TODO_ITEM = 'ADD_TODO_ITEM'
export const DELETE_TODO_INTEM = 'DELETE_TODO_INTEM'
export const INIT_LIST_ACTION = 'INIT_LIST_ACTION'
